# Generated by Django 5.2.7 on 2025-12-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=16)),
                ('league_display', models.CharField(max_length=16)),
                ('sport', models.CharField(max_length=16)),
                ('check_type', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], max_length=8)),
                ('check_day', models.IntegerField(blank=True, null=True)),
                ('season_types', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.DateField()),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('is_offseason', models.BooleanField()),
                ('all_star_start', models.DateField(blank=True, null=True)),
                ('all_star_end', models.DateField(blank=True, null=True)),
                ('season_type', models.IntegerField(choices=[(2, 'Regular Season'), (3, 'Post Season')])),
                ('week', models.IntegerField(blank=True, null=True)),
                ('league_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_collection_state', to='core.leaguedetails')),
            ],
        ),
    ]
