# Generated by Django 5.2.7 on 2025-10-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('college-football', 'NCAAF'), ('nfl', 'NFL'), ('nba', 'NBA'), ('wnba', 'WNBA'), ('mlb', 'MLB')], max_length=16)),
                ('collected', models.DateField()),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('all_star_start', models.DateField()),
                ('all_star_end', models.DateField()),
                ('season_type', models.IntegerField(choices=[(2, 'Regular Season'), (3, 'Post Season')])),
                ('week', models.IntegerField()),
            ],
        ),
    ]
