# Generated by Django 5.2.7 on 2025-10-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectionstate',
            name='all_star_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacollectionstate',
            name='all_star_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacollectionstate',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
