# Generated by Django 5.2.7 on 2025-12-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leaguenamepair_remove_leaguedetails_league_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguedetails',
            old_name='season_types',
            new_name='season_types_json',
        ),
    ]
