# Generated by Django 5.2.7 on 2025-12-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_season_types_leaguedetails_season_types_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacollectionstate',
            old_name='collected',
            new_name='collection_date',
        ),
        migrations.AddField(
            model_name='datacollectionstate',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
