# Generated by Django 5.2.7 on 2025-12-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_collected_datacollectionstate_collection_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueNamePair',
        ),
        migrations.AlterField(
            model_name='leaguedetails',
            name='league',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
