# Generated by Django 5.2.7 on 2025-12-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_leaguenamepair_alter_leaguedetails_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedetails',
            name='league_display',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
