# Generated by Django 5.2.7 on 2025-12-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leaguedetails_league_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguedetails',
            options={'ordering': ['league_display']},
        ),
        migrations.AlterField(
            model_name='leaguedetails',
            name='league_display',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
