# Generated by Django 5.2.7 on 2026-01-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_leaguedetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_name', models.CharField(max_length=16, unique=True)),
                ('league_display', models.CharField(max_length=16, unique=True)),
                ('sport', models.CharField(max_length=16)),
                ('_check_type', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], max_length=8)),
                ('check_day', models.IntegerField(blank=True, null=True)),
                ('_season_types', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['league_display'],
            },
        ),
        migrations.DeleteModel(
            name='DataCollectionState',
        ),
        migrations.DeleteModel(
            name='LeagueDetails',
        ),
    ]
