# Generated by Django 5.2.7 on 2026-01-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_league_delete_datacollectionstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_name', models.CharField(max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=16, unique=True)),
                ('sport', models.CharField(max_length=16)),
                ('_check_type', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], max_length=8)),
                ('check_day', models.IntegerField(blank=True, null=True)),
                ('_season_types', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'League Details',
                'verbose_name_plural': 'League Details',
                'ordering': ['display_name'],
            },
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
