# Generated by Django 5.2.6 on 2025-09-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('college-football', 'NCAAF'), ('nfl', 'NFL'), ('nba', 'NBA'), ('mlb', 'MLB')], max_length=16)),
                ('espn_id', models.CharField(max_length=24)),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('week', models.IntegerField(null=True)),
                ('season_type', models.IntegerField(choices=[(2, 'Regular Season'), (3, 'Post Season')])),
                ('home_team', models.CharField(max_length=128)),
                ('home_rank', models.IntegerField(null=True)),
                ('home_win_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('home_moneyline', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('is_home_win', models.BooleanField(default=False)),
                ('away_team', models.CharField(max_length=128)),
                ('away_rank', models.IntegerField(null=True)),
                ('away_win_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_moneyline', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('is_away_win', models.BooleanField(default=False)),
                ('is_neutral_site', models.BooleanField(default=False)),
                ('both_ranked_matchup', models.BooleanField(default=False)),
                ('one_ranked_matchup', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('league', 'espn_id'), name='unique_league_event_id_combination')],
            },
        ),
    ]
