# Generated by Django 5.2.6 on 2025-09-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['league', '-espn_id']},
        ),
        migrations.AddField(
            model_name='event',
            name='winning_team',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='TeamPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128)),
                ('team_rank', models.IntegerField(blank=True, null=True)),
                ('home_away', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('neutral', 'Neutral')], max_length=8)),
                ('win_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moneyline', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_winner', models.BooleanField()),
                ('opponent_name', models.CharField(max_length=128)),
                ('opponent_rank', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='eventdata.event')),
            ],
            options={
                'ordering': ['event__league', 'event__date', '-event__espn_id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'team_name'), name='unique_event_team_combination')],
            },
        ),
    ]
