# Generated by Django 5.2.6 on 2025-09-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0003_event_to_team_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='away_moneyline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='away_rank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='away_win_probability',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_moneyline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_rank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_win_probability',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_away_win',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_home_win',
        ),
    ]
