# Generated by Django 5.2.7 on 2025-10-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0004_remove_event_away_moneyline_remove_event_away_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='league',
            field=models.CharField(choices=[('college-football', 'NCAAF'), ('nfl', 'NFL'), ('nba', 'NBA'), ('wnba', 'WNBA'), ('mlb', 'MLB')], max_length=16),
        ),
    ]
