# Generated by Django 5.2.7 on 2025-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0005_alter_event_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='league',
            field=models.CharField(max_length=16),
        ),
    ]
